### ISSUE TITLE
attempt to concatenate a nil value

### ISSUE THREAD

**Issue by inferrna** [BuckarooBanzay/citygen#2]
Got error
![image](https://user-images.githubusercontent.com/4245277/131013049-6170f5f7-40a9-47aa-97c4-a00ade3994bf.png)

In Dreambuilder game with those mods:
![image](https://user-images.githubusercontent.com/4245277/131014618-b1cd08b3-63c7-4ce7-847f-15b83392908f.png)

**Comment by IrrlichtMt4** [comment]
Seems a lot of people are getting this error. I will test in 5.5.0-stable.

**Comment by BuckarooBanzay** [comment]
sorry for the late response, the notifications were turned off, is this still and issue?
