### ISSUE TITLE
Citygen mod keeps returning these asert errors

### ISSUE THREAD

**Issue by ngalerchalegocity60330** [BuckarooBanzay/citygen#5]
Minetest 5.5.0 flatpak version. All of the optional dependencies were also installed.

AsyncErr: Lua: Runtime error from mod 'citygen' in callback environment_OnGenerated(): /home/####/.minetest/mods/citygen/layout.lua:37: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/home/####/.minetest/mods/citygen/layout.lua:37: in function 'create_building'
	/home/####/.minetest/mods/citygen/layout.lua:151: in function 'create_layout'
	/home/####/.minetest/mods/citygen/cityblock.lua:33: in function 'get_cityblock'
	/home/####/.minetest/mods/citygen/cityblock.lua:7: in function 'get_cityblock_mapblock'
	/home/####/.minetest/mods/citygen/mapgen.lua:10: in function </home/####/.minetest/mods/citygen/mapgen.lua:2>
	/app/share/minetest/builtin/game/register.lua:425: in function </app/share/minetest/builtin/game/register.lua:409>

**Comment by IrrlichtMt4** [comment]
Did you try setting the mapgen to singlenode?

**Comment by MisterE123** [comment]
I get the following error:
```
AsyncErr: Lua: Runtime error from mod 'citygen' in callback environment_OnGenerated(): ...etest-5.6.0-e765988-win64\bin\..\mods\citygen/layout.lua:37: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...etest-5.6.0-e765988-win64\bin\..\mods\citygen/layout.lua:37: in function 'create_building'
	...etest-5.6.0-e765988-win64\bin\..\mods\citygen/layout.lua:151: in function 'create_layout'
	...st-5.6.0-e765988-win64\bin\..\mods\citygen/cityblock.lua:33: in function 'get_cityblock'
	...st-5.6.0-e765988-win64\bin\..\mods\citygen/cityblock.lua:7: in function 'get_cityblock_mapblock'
	...etest-5.6.0-e765988-win64\bin\..\mods\citygen/mapgen.lua:10: in function <...etest-5.6.0-e765988-win64\bin\..\mods\citygen/mapgen.lua:2>
	...est-5.6.0-e765988-win64\bin\..\builtin\game\register.lua:425: in function <...est-5.6.0-e765988-win64\bin\..\builtin\game\register.lua:409>
```

And, yes, I am quite sure that singlenode mapgen is enabled.

**Comment by BuckarooBanzay** [comment]
Same as #4, sorry for the delay:

> sorry for the late response, looks like i turned off the notifications for this repo :P
Anyway: in the current state this mod can only function with registered buildings, those require the `moreblocks` and `default` mod to be present, i re-added them to the hard-deps again, please try again with those mods enabled/installed
